### ISSUE TITLE
A random error appears for no reason

### ISSUE THREAD

**Issue by LordLucass** [r4g3baby/SimpleScore#1]
**[22:59:47 WARN]: [SimpleScore] Task #33 for SimpleScore v3.3.2 generated an exception
java.lang.IllegalArgumentException: Count 'n' must be non-negative, but was -1.
at com.r4g3baby.simplescore.shaded.kotlin.text.StringsKt__StringsJVMKt.repeat(StringsJVM.kt:629) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardRunnable.replaceVariables(ScoreboardRunnable.kt:72) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardRunnable.run(ScoreboardRunnable.kt:27) ~[?:?]
at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]**

It just happens for no apparent reason, floods my console, but it doesn't affect anything ... I just wanted it to stop flooding because I interact with other plugins and need to know the results.

Config.yml: https://paste.gg/p/anonymous/3e4f951afd184f4cbf07fdfb72337f03
Messages.yml: Default archive

**Comment by r4g3baby** [comment]
This issue has been already been fixed, please update to the latest plugin version.

**Comment by LordLucass** [comment]
Thank u

**Comment by LordLucass** [comment]
**[11:31:31 WARN]: [SimpleScore] Task #33 for SimpleScore v3.3.2 generated an exception
java.lang.IllegalArgumentException: Count 'n' must be non-negative, but was -1.
at com.r4g3baby.simplescore.shaded.kotlin.text.StringsKt__StringsJVMKt.repeat(StringsJVM.kt:629) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardRunnable.replaceVariables(ScoreboardRunnable.kt:72) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardRunnable.run(ScoreboardRunnable.kt:27) ~[?:?]
at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]**


Print: https://prnt.sc/v34z9y

Scoreboard updated, the problem persists...

My scoreboard version: Latest (3.4.1)
Version: 1.12.2 - R.0.1 - Snapshot
