### ISSUE TITLE
1.17 Console Spam

### ISSUE THREAD

**Issue by PremiereSetups** [r4g3baby/SimpleScore#10]
Hey, after I put in the new version of protcolib for 1.17 the plugin seemed to kinda loose it's mind, I didn't see an option to turn off protocolib integration. I am on Spigot 1.17.

`[10:39:02] [Server thread/WARN]: [SimpleScore] Task #9847 for SimpleScore v3.7.2 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboard(ScoreboardManager.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask$run$4.run(ScoreboardTask.kt:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:39:02] [Server thread/WARN]: [SimpleScore] Task #9848 for SimpleScore v3.7.2 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboard(ScoreboardManager.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask$run$4.run(ScoreboardTask.kt:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:39:02] [Server thread/WARN]: [SimpleScore] Task #9849 for SimpleScore v3.7.2 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboard(ScoreboardManager.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask$run$4.run(ScoreboardTask.kt:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:39:02] [Server thread/WARN]: [SimpleScore] Task #9850 for SimpleScore v3.7.2 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboard(ScoreboardManager.kt:107) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask$run$4.run(ScoreboardTask.kt:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by r4g3baby** [comment]
Hey, plugin hasn't been updated to 1.17 yet. I'll try and get to it over the next few days.

**Comment by r4g3baby** [comment]
Caused by dmulloy2/ProtocolLib#1232. Plugin should work just fine as soon as ProtocolLib comes up with a fix, a workaround is to not use ProtocolLib or use ``ForceLegacy: true`` in the config.
