### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by MrSuricate2** [r4g3baby/SimpleScore#11]
Hello,
My server is in 1.12.2 and I use the plugin in version 3.7.2

In the console I have this spam message:

`[SimpleScore] Plugin SimpleScore v3.7.2 generated an exception while executing task 92
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getPlayers(CraftWorld.java:793) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by r4g3baby** [comment]
Hey, does this happen as soon as someone joins the server and does it keep on spamming until they leave?

**Comment by r4g3baby** [comment]
I'm closing this issue. If you're still having problems feel free to reopen.
