### ISSUE TITLE
Whenever a player leaves the server, SimpelScore returns an error on the Console

### ISSUE THREAD

**Issue by LordLucass** [r4g3baby/SimpleScore#2]
**[15:54:15 ERROR]: Could not pass event PlayerQuitEvent to SimpleScore v3.4.1
org.bukkit.event.EventException: null
at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1167) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:361) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.IllegalArgumentException: cannot send packets to a closed channel
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1618]
at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:683) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:675) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:401) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.removeScoreboard(ProtocolScoreboard.kt:39) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.listeners.PlayersListener.onPlayerQuit(PlayersListener.kt:19) ~[?:?]
at sun.reflect.GeneratedMethodAccessor905.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) ~[?:?]
... 11 more**

Whenever a player leaves the server he ends up giving the error above, when the player enters no error occurs and it works normal, only when he leaves

Informations:
Version: 1.12.-R.0.1-SnapShot
Plugin Version: Latest (3.4.1)
How to reproduce the error: Just getting in and out of the server.

Please help

PS. Sorry my bad english, i'm brazilian

**Comment by r4g3baby** [comment]
I haven't been able to replicate this locally yet. What ProtocolLib version are you using?

**Comment by LordLucass** [comment]
I'm already using "4.5.1" from ProtocolLib.

**Comment by r4g3baby** [comment]
Here can you try downloading this version and let me know if it fixes the issue.
https://gofile.io/d/3696gk

**Comment by LordLucass** [comment]
Okay, in a few minutes I'll give you the answer

**Comment by LordLucass** [comment]
The same error occurred:

**<-> DownstreamBridge <-> [skyblock] - encountered exception
java.lang.IllegalArgumentException: Objective sbaeab981d0d874b already exists in this scoreboard
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:170) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:67) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
>.... [16:37:29 INFO]: [terapoide] disconnected with: The server you were previously on went down, you have been connected to a fallback server**

**Comment by r4g3baby** [comment]
That's a different issue, the updated version I sent is supposed to fix the issue you were getting on your server whenever someone left the server.

Can you send me a copy of your config file please.

**Comment by LordLucass** [comment]
Yes, here's a copy of my SimpleScore config.yml. The messages.yml is standard for the plugin, nothing has been changed in it.

Link: https://paste.gg/p/anonymous/ef9be1a7298643979f13a35dd1d814fa

**Comment by r4g3baby** [comment]
Can you restart your waterfall proxy and check if the issue still persists.

**Comment by LordLucass** [comment]
I'll do it. 1 minute.

**Comment by LordLucass** [comment]
Done ... all servers have been restarted (skyblock, lobby, bungeecord) and the error still persists. It is worth noting that it only occurs when I change warp (I'm using EssentialsX) ... oh, this may be futile, but, is it likely to be a corrupted file?

**Comment by r4g3baby** [comment]
Oh, so this happens when you change worlds?

**Comment by LordLucass** [comment]
**<-> DownstreamBridge <-> [skyblock] - encountered exception
java.lang.IllegalArgumentException: Objective sb23ccd25a9ba543 already exists in this scoreboard
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:170) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:67) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4d36935:347]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
>.... [16:57:34 INFO]: [menina_angelical] disconnected with: The server you were previously on went down, you have been connected to a fallback server**

**Comment by LordLucass** [comment]
Yes, only when I change the world, I can interact with the environment normally, however, when I type /warp shop (example), or /spawn, I get kicked and this error appears in the bungeecord.

**Comment by r4g3baby** [comment]
Ok, I think I might know what's going on then give me a few minutes to come up with a solution.

**Comment by LordLucass** [comment]
I'm waiting.

**Comment by r4g3baby** [comment]
Here let me know if this fixes the issue.
https://gofile.io/d/crKniw

**Comment by LordLucass** [comment]
Ok. I removed the old "SimpleScore-3.4.2-beta1.jar" and added the new one. I installed the server. It seems that everything went well! No errors were announced in either Skyblock or Bungeecord. I teleported to all warps on the server and no errors occurred, I wasn't even kicked! You do miracles, see?

**Comment by LordLucass** [comment]
Thanks again for support. Your plugin is worthy of a beautiful use.

**Comment by r4g3baby** [comment]
Glad it's all working now. Thank you for your help and patience.
I'll post an update to spigot in a bit with this fixes.
If you would like to support my work starring the project here on GitHub and/or giving a review on spigot would be appreciated.

**Comment by LordLucass** [comment]
We will gladly evaluate your plugin.
