### ISSUE TITLE
SimpleScore - Works with 1.18 tho spits:spams console with and version error it seems!

### ISSUE THREAD

**Issue by nexnux** [r4g3baby/SimpleScore#27]
Console output when player joins server - SimpleScore is working and shows the overall scoreboard!

`[08:12:52] [Server thread/WARN]: [SimpleScore] Could not apply PlaceholderAPI placeholders
java.lang.RuntimeException: Failed to determine Minecraft version
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:410) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:79) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:58) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:121) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:386) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:319) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-9(ScoreboardTask.kt:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No match found in 'dev-Spigot-b11f318-9fb3aa4 (MC: 1.18 Release Candidate 3)'
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:407) ~[?:?]
        ... 20 more
[08:12:57] [Server thread/WARN]: [SimpleScore] Could not apply PlaceholderAPI placeholders
java.lang.RuntimeException: Failed to determine Minecraft version
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:410) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:79) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:58) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:121) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:386) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:319) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-9(ScoreboardTask.kt:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No match found in 'dev-Spigot-b11f318-9fb3aa4 (MC: 1.18 Release Candidate 3)'
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:407) ~[?:?]
        ... 20 more
[08:13:02] [Server thread/WARN]: [SimpleScore] Could not apply PlaceholderAPI placeholders
java.lang.RuntimeException: Failed to determine Minecraft version
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:410) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:79) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:58) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:121) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:386) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:319) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-9(ScoreboardTask.kt:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No match found in 'dev-Spigot-b11f318-9fb3aa4 (MC: 1.18 Release Candidate 3)'
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:407) ~[?:?]
        ... 20 more
[08:13:07] [Server thread/WARN]: [SimpleScore] Could not apply PlaceholderAPI placeholders
java.lang.RuntimeException: Failed to determine Minecraft version
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:410) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.cacheReflection(PlayerUtil.java:79) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:58) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:121) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:386) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:319) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-9(ScoreboardTask.kt:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-rc3-R0.1-SNAPSHOT.jar:dev-Spigot-b11f318-9fb3aa4]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No match found in 'dev-Spigot-b11f318-9fb3aa4 (MC: 1.18 Release Candidate 3)'
        at com.extendedclip.papi.expansion.player.PlayerExpansion.minecraftVersion(PlayerExpansion.java:407) ~[?:?]
        ... 20 more
`

**Comment by r4g3baby** [comment]
Hey, this isn't a problem with SimpleScore but one of the PlaceholderAPI expansions you are using (more concrectly the PlayerExpansion). Contact PlaceholderAPI or the developer of the expansion for a fix.
