### ISSUE TITLE
Warning From SimpleScore 3.8.1

### ISSUE THREAD

**Issue by andhra21231** [r4g3baby/SimpleScore#28]
[02:12:45 WARN]: [SimpleScore] Plugin SimpleScore v3.8.1 generated an exception while executing task 48
java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller
        at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[PlaceholderAPI-2.10.6.jar:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[PlaceholderAPI-2.10.6.jar:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
        at com.extendedclip.papi.expansion.javascript.evaluator.NashornScriptEvaluator.execute(NashornScriptEvaluator.java:30) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptPlaceholder.evaluate(JavascriptPlaceholder.java:120) ~[?:?]
        at com.extendedclip.papi.expansion.javascript.JavascriptExpansion.onRequest(JavascriptExpansion.java:157) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[PlaceholderAPI-2.10.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525) ~[PlaceholderAPI-2.10.6.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:107) ~[SimpleScore-3.8.1.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.applyPlaceholders(ScoreboardTask.kt:96) ~[SimpleScore-3.8.1.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:70) ~[SimpleScore-3.8.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by andhra21231** [comment]
Im Using : 

1.17.1 Pufferfish

Java 17

**Comment by r4g3baby** [comment]
Hey, that's a problem with one of the placeholders you are using. You need to figure out what placeholder is causing this error and contact the developer of the extension or plugin of said placeholder.
