### ISSUE TITLE
exception while executing task 64 java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by Klawdek** [r4g3baby/SimpleScore#45]
I do not know how to duplicate this it just happened while nobody was on the server.  I have been running simplescore for about a month with no problems.
`21.06 10:49:46 [Server] WARN Plugin SimpleScore v3.11.1 generated an exception while executing task 64
21.06 10:49:46 [Server] INFO java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
21.06 10:49:46 [Server] INFO at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
21.06 10:49:46 [Server] INFO at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
21.06 10:49:46 [Server] INFO at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
21.06 10:49:46 [Server] INFO at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
21.06 10:49:46 [Server] INFO at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
21.06 10:49:46 [Server] INFO at com.r4g3baby.simplescore.scoreboard.models.ScoreFrames.tick(ScoreFrames.kt:17) ~[SimpleScore-3.11.1.jar:?]
21.06 10:49:46 [Server] INFO at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:20) ~[SimpleScore-3.11.1.jar:?]
21.06 10:49:46 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-329]
21.06 10:49:46 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-329]
21.06 10:49:46 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-329]
21.06 10:49:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
21.06 10:49:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
21.06 10:49:46 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by r4g3baby** [comment]
Hey, is this error constantly happening now or has it stopped?

**Comment by r4g3baby** [comment]
Closing due to inactivity. If this is still an issue feel free to re-open.

**Comment by Klawdek** [comment]
It happens  every day

14.07 16:51:39 [Server] WARN Plugin SimpleScore v3.11.1 generated an exception while executing task 65
14.07 16:51:39 [Server] INFO java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
14.07 16:51:39 [Server] INFO at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
14.07 16:51:39 [Server] INFO at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
14.07 16:51:39 [Server] INFO at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
14.07 16:51:39 [Server] INFO at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
14.07 16:51:39 [Server] INFO at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
14.07 16:51:39 [Server] INFO at com.r4g3baby.simplescore.scoreboard.models.ScoreFrames.tick(ScoreFrames.kt:17) ~[SimpleScore-3.11.1.jar:?]
14.07 16:51:39 [Server] INFO at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:20) ~[SimpleScore-3.11.1.jar:?]
14.07 16:51:39 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
14.07 16:51:39 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
14.07 16:51:39 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
14.07 16:51:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
14.07 16:51:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
14.07 16:51:39 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by r4g3baby** [comment]
Update your plugin to the latest version (currently 3.12.0)
