### ISSUE TITLE
error Code

### ISSUE THREAD

**Issue by SladeGit** [r4g3baby/SimpleScore#48]
if I e.g. one over the Console an write with /tell...

then I get the following error message:

java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.models.PlayerLine.getShouldRender(PlayerLine.kt:22) ~[SimpleScore-3.12.1.jar:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboard(ScoreboardTask.kt:132) ~[SimpleScore-3.12.1.jar:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboards(ScoreboardTask.kt:101) ~[SimpleScore-3.12.1.jar:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-8(ScoreboardTask.kt:75) ~[SimpleScore-3.12.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1492) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by r4g3baby** [comment]
Hey, can you send me a copy of your configuration files and the server latest.log please.

Does this happen often or do you have a way to trigger this error that I can replicate?

**Comment by r4g3baby** [comment]
Closing this issue due to inactivity, feel free to re-open at any time with the information needed to replicate this.
