### ISSUE TITLE
error code again

### ISSUE THREAD

**Issue by SladeGit** [r4g3baby/SimpleScore#49]
latest paperspigot
latest simplescore plugin
mc 1.19.2

error come when resrating and the first player join.

[19:07:32 WARN]: [SimpleScore] Task #3366 for SimpleScore v3.12.2 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.models.PlayerLine.getCurrentText(PlayerLine.kt:13) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboard(ScoreboardTask.kt:135) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboards(ScoreboardTask.kt:101) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-8(ScoreboardTask.kt:75) ~[SimpleScore-3.12.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-174]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-174]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by r4g3baby** [comment]
Please send a copy of your scoreboards config.

**Comment by SladeGit** [comment]
i do it next day

**Comment by SladeGit** [comment]
simple:
  titles: '&a&LGreen&4&lLand'
  scores:
    '13':
    - '  &7&m+-------------+'
    - '  &7&m---------------'
    '12': '&7&l｜&4&lClaims'
    '11': '  &7&l»&a %ultimateclaims_totalchunks%'
    '10': ''
    '9': '&7&l｜&4&lCoins ⛃'
    '8': '  &7&l»&a %vault_eco_balance_formatted%'
    '7': ''
    '6': '&7&l｜&4&lJob'
    '5': '  &7&l»&a %jobsr_user_jobs% lvl: %jobsr_user_totallevels%/25'
    '4': ''
    '3': '&7&l｜&4&lMarry'
    '2': '  &7&l»&a %marriagemaster_IsMarried%'
    '1':
    - '  &7&m+-------------+'
    - '  &7&m---------------'

# Scoreboard with a basic timing example
customTiming:
  # Any frame without a specified update/render time will default to this values
  updateTime: 100
  renderTime: 50
  titles:
    # This frame will show for 200 ticks and render every 50 ticks (4 times)
    - text: '&c200 ticks/10 seconds title'
      update: 200
    # While this frame will show for 100 ticks and render every 20 ticks (5 times)
    - text: '&a100 ticks/5 seconds title'
      render: 20
  scores:
    6: '&7You can set a per title and score time'
    5: '&7instead of using the default value'
    4: ''
    3:
      - text: '&7This will last for &810 seconds'
        update: 200
      - text: '&7while this only lasts for &85 seconds'
    2: ''
    1:
      # These frames will change every 60 ticks/3 seconds and will only render once on change
      - text: '&6Your current world is &7%world%&6.'
        update: 60
        render: 60
      - text: '&6There are &7%online% &6players online.'
        update: 60
        render: 60

# Scoreboard showing how conditions work
conditional:
  updateTime: 60
  conditions: [ 'hasPermission' ]
  titles: '&cConditional Scoreboard'
  scores:
    9: ''
    8: '&7Scoreboards with a list of conditions require'
    7: '&7that the player passes all of them.'
    6: ''
    5: '&7You can see this scoreboard because you'
    4: '&7passed the &8hasPermission &7condition.'
    3: ''
    2:
      conditions: [ 'isOverworld' ]
      frames:
        - '&7You can see this line because you..'
        - '&7passed the &8isOverworld &7condition.'
      else:
        conditions: [ 'isTheEnd' ]
        frames:
          - '&7You can see this line because you..'
          - '&7passed the &8isTheEnd &7condition but..'
          - '&7didn''t pass the &8isOverworld &7condition.'
        else: '&7You didn''t pass any of the conditions.'
    1: ''

**Comment by SladeGit** [comment]
And can u help me, if i use the placeholder "%vault_eco_balance_formatted%" on connect ist takes long time to show the Right

**Comment by r4g3baby** [comment]
Sorry for the late reply, but I'm not sure what's causing the error you are having and even using your config doesn't seem to happen to me.
How often does this error happen, is there a specific situation that causes it?


> And can u help me, if i use the placeholder "%vault_eco_balance_formatted%" on connect ist takes long time to show the Right
Not sure what you mean by that however placeholders are provided by other plugins, if they aren't displaying the information you want then you will need to reach out to the developer of the plugin whose placeholders you are using.
