### ISSUE TITLE
Bug server Spigot 1.20.1

### ISSUE THREAD

**Issue by MrDciBelia** [r4g3baby/SimpleScore#65]
### Plugin Version

3.12.2

### Server Version

Spigot 1.20.1

### Describe the Bug

Problem with version 3.12.2 on my server spigot 1.20.1, not work

### Relevant Log Output

```shell
[WARN] [SimpleScore] Could not apply PlaceholderAPI placeholders
java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
at jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132) ~[?:?]
at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.getInt(UnsafeQualifiedObjectFieldAccessorImpl.java:59) ~[?:?]
at java.lang.reflect.Field.getInt(Field.java:601) ~[?:?]
at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:65) ~[?:?]
at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:49) ~[?:?]
at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:121) ~[?:?]
at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:392) ~[?:?]
at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:325) ~[?:?]
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.placeholders.PlaceholderReplacer.applyPlaceholderAPI(PlaceholderReplacer.kt:23) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.placeholders.PlaceholderReplacer.replace(PlaceholderReplacer.kt:13) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:146) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboard(ScoreboardTask.kt:134) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboards(ScoreboardTask.kt:101) ~[?:?]
at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda-8(ScoreboardTask.kt:75) ~[?:?]
at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1256) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by r4g3baby** [comment]
Hey, that's not a problem with SimpleScore. It's due to the PlayerUtil expansion for PlaceholderAPI and their ping placeholder, it seems to not be working properly. You will need to contact the developer of that expansion or check if there isn't a newer version of said expansion.
