### ISSUE TITLE
 [SimpleScore] Could not apply PlaceholderAPI placeholders

### ISSUE THREAD

**Issue by VillagerBoyGitHub** [r4g3baby/SimpleScore#66]
### Plugin Version

v3.12.2

### Server Version

1.20.2-R0.1-SNAPSHOT

### Describe the Bug

This error message keeps coming up...

### Relevant Log Output

```shell
java.lang.IllegalArgumentException: Attempt to get boolean field "net.minecraft.server.level.EntityPlayer.f" with illegal data type conversion to int
        at jdk.internal.reflect.FieldAccessorImpl.newGetIllegalArgumentException(FieldAccessorImpl.java:130) ~[?:?]
        at jdk.internal.reflect.FieldAccessorImpl.newGetIntIllegalArgumentException(FieldAccessorImpl.java:193) ~[?:?]
        at jdk.internal.reflect.MethodHandleBooleanFieldAccessorImpl.getInt(MethodHandleBooleanFieldAccessorImpl.java:87) ~[?:?]
        at java.lang.reflect.Field.getInt(Field.java:628) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:131) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481) ~[?:?]
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.4.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.4.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.4.jar:?]
        at com.r4g3baby.simplescore.scoreboard.placeholders.PlaceholderReplacer.applyPlaceholderAPI(PlaceholderReplacer.kt:23) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.placeholders.PlaceholderReplacer.replace(PlaceholderReplacer.kt:13) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.replacePlaceholders(ScoreboardTask.kt:146) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboard(ScoreboardTask.kt:134) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.getPlayerScoreboards(ScoreboardTask.kt:101) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:69) ~[SimpleScore-3.12.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-223]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-223]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by r4g3baby** [comment]
Hey, that's not a problem with SimpleScore. It's due to the PlayerUtil expansion for PlaceholderAPI and their ping placeholder, it seems to not be working properly. You will need to contact the developer of that expansion or check if there isn't a newer version of said expansion.
