### ISSUE TITLE
Errors in 1.20.2

### ISSUE THREAD

**Issue by twk1024** [r4g3baby/SimpleScore#67]
### Plugin Version

3.12.2

### Server Version

git-Paper-233 (MC: 1.20.2)

### Describe the Bug

I am using the latest Paper build and the latest developmental build of ProtocolLib.
However, when I join my server, the plugin displays some error.

And when I start moving, another error displays and kicks me out.

I've removed all of my config and scoreboard settings and tried again, but the same results.

### Relevant Log Output

```shell
When I join the server:

[21:00:43] [Server thread/INFO]: ddongterry[/] logged in with entity id 40 at ([world]-133.24266581291732, 23.0, 209.9269955479423)
[21:00:45] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to SimpleScore v3.12.2
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda-0(ProtocolScoreboard.kt:38) ~[SimpleScore-3.12.2.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:26) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.listeners.PlayerListener.onPlayerMove(PlayerListener.kt:43) ~[SimpleScore-3.12.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-233]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-233]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-233]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1535) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-233]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]



When I move in the server:

[21:00:45] [Server thread/INFO]: ddongterry lost connection: Disconnected
[21:00:45] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SimpleScore v3.12.2
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda-0(ProtocolScoreboard.kt:38) ~[SimpleScore-3.12.2.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:26) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore$default(ScoreboardManager.kt:86) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:232) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:228) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.ScoreboardManager$PlayersData.setDisabled(ScoreboardManager.kt:227) ~[SimpleScore-3.12.2.jar:?]
	at com.r4g3baby.simplescore.scoreboard.listeners.PacketListener.onPlayerQuit(PacketListener.kt:64) ~[SimpleScore-3.12.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor306.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-233]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-233]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-233]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:594) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:579) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2065) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2045) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2032) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:837) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:260) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-233]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-233]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[21:00:45] [Server thread/INFO]: • ddongterry
```

**Comment by r4g3baby** [comment]
Thank you for reporting this!
An update has been published with a fix for this issue, https://www.spigotmc.org/resources/simplescore-animated-scoreboard.23243/update?update=519789
