### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by M0diis** [r4g3baby/SimpleScore#71]
### Plugin Version

v3.12.3

### Server Version

git-Pufferfish-32 (MC: 1.20.2)

### Describe the Bug

Error on player join. Info in the stacktrace.

### Relevant Log Output

```shell
java.lang.IllegalArgumentException: No enum constant org.bukkit.scoreboard.DisplaySlot.LIST
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:860) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:846) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:301) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:251) ~[ProtocolLib-#2589.jar:?]
	at com.r4g3baby.simplescore.scoreboard.listeners.PacketListener.onPacketSending(PacketListener.kt:38) ~[SimpleScore-3.12.3.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib-#2589.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib-#2589.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection$PacketSendAction.lambda$new$0(Connection.java:956) ~[?:?]
	at net.minecraft.network.Connection$WrappedConsumer.accept(Connection.java:940) ~[?:?]
	at net.minecraft.network.Connection.processQueue(Connection.java:562) ~[?:?]
	at net.minecraft.network.Connection.flushQueue(Connection.java:523) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:412) ~[?:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:242) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:227) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.froobworld.viewdistancetweaks.lib.joor.Reflect.on(Reflect.java:906) ~[ViewDistanceTweaks-1.5.7.jar:?]
	at com.froobworld.viewdistancetweaks.lib.joor.Reflect.call(Reflect.java:583) ~[ViewDistanceTweaks-1.5.7.jar:?]
	at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.sendViewDistance(ClientViewDistanceManager.java:68) ~[ViewDistanceTweaks-1.5.7.jar:?]
	at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.sendOptimisticViewDistance(ClientViewDistanceManager.java:59) ~[ViewDistanceTweaks-1.5.7.jar:?]
	at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.onPlayerJoin(ClientViewDistanceManager.java:88) ~[ViewDistanceTweaks-1.5.7.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:git-Pufferfish-32]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1326) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1303) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1296) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1274) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1162) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[pufferfish-1.20.2.jar:git-Pufferfish-32]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:02:49] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutScoreboardDisplayObjective@66b831b0[
    a=LIST
    b=TAB-YellowNumber
  ]
```

**Comment by mattcapazz** [comment]
Version [3.12.4](https://github.com/r4g3baby/SimpleScore/releases/download/v3.12.4/SimpleScore-3.12.4.jar) of SimpleScore fixes this issue.

**Comment by M0diis** [comment]
Wasn't posted on Spigot. Thanks. :)
