### ISSUE TITLE
Exception in thread "Craft Scheduler Thread - 3"

### ISSUE THREAD

**Issue by josealissonbr** [r4g3baby/SimpleScore#73]
### Plugin Version

v3.12.5

### Server Version

Spigot 1.8.8

### Describe the Bug

I didn't find a reason for the exception, but out of nowhere I get this in the console sometimes.

### Relevant Log Output

```shell
[04:14:54 WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[04:14:54 WARN]: org.apache.commons.lang.UnhandledException: Plugin SimpleScore v3.12.5 generated an exception while executing task 96
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
        at java.util.ArrayList$Itr.next(ArrayList.java:861)
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getPlayers(CraftWorld.java:755)
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run(ScoreboardTask.kt:23)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
```

**Comment by RuiPereiraDev** [comment]
Hey! Sorry for the delayed response, but I've been away.

[SimpleScore v4](https://modrinth.com/plugin/simplescore/version/4.0.0) should resolve this issue. If not, please feel free to reopen it!
