### ISSUE TITLE
NPE on attempt to post scoreboard

### ISSUE THREAD

**Issue by SlimeDog** [r4g3baby/SimpleScore#79]
### Plugin Version

3.12.5

### Server Version

Paper 1.20.6-64

### Describe the Bug

No errors on server start-up. When a player tries to display a scoreboard, errors ensue.

### Relevant Log Output

```shell
[14:48:20 ERROR]: Could not pass event PlayerJoinEvent to SimpleScore v3.12.5
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundSetObjectivePacket - true - com.comphenix.protocol.wrappers.WrappedStreamCodec[handle=net.minecraft.network.codec.StreamCodec$5@1117c444]
        at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.StructureCache.lambda$newPacket$4(StructureCache.java:130) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:134) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:144) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:119) ~[ProtocolLib-5.2.1-b689.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:30) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda$0(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710) ~[?:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore$default(ScoreboardManager.kt:86) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.listeners.PlayerListener.onPlayerJoin(PlayerListener.kt:18) ~[SimpleScore-3.12.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor452.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-64]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:git-Paper-64]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-64]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[paper-1.20.6.jar:git-Paper-64]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-64]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
```

**Comment by SlimeDog** [comment]
Abandoned. Closing ...
