### ISSUE TITLE
Could not pass event PlayerMoveEvent to SimpleScore v3.12.5

### ISSUE THREAD

**Issue by yusufklncc** [r4g3baby/SimpleScore#81]
### Plugin Version

v3.12.5

### Server Version

1.20.6-R0.1

### Describe the Bug

![image](https://github.com/r4g3baby/SimpleScore/assets/78423442/1178c2f2-d1c2-4f53-be7d-19dcadaf03a2)
I get this error when I create an NPC in my world with an NPC plugin (FancyNPCs, CustomNPCs). I don't see this error on the console when there is no one in the server or when it's not moving, but when it starts moving it keeps giving me this error.

### Relevant Log Output

```shell
[14:39:55] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to SimpleScore v3.12.5
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundSetObjectivePacket - true - com.comphenix.protocol.wrappers.WrappedStreamCodec[handle=net.minecraft.network.codec.StreamCodec$5@448491ac]
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.lambda$newPacket$4(StructureCache.java:130) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:134) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:144) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:119) ~[ProtocolLib.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:30) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda$0(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710) ~[?:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.listeners.PlayerListener.onPlayerMove(PlayerListener.kt:43) ~[SimpleScore-3.12.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor110.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-81-5a9afbe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1567) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1514) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1414) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-81-5a9afbe]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by RuiPereiraDev** [comment]
Hey! Sorry for the delayed response, but I've been away.

[SimpleScore v4](https://modrinth.com/plugin/simplescore/version/4.0.0) should resolve this issue. If not, please feel free to reopen it!
