### ISSUE TITLE
Could not pass event PlayerJoinEvent to SimpleScore v3.12.5

### ISSUE THREAD

**Issue by GalaxyGamerYT** [r4g3baby/SimpleScore#82]
### Plugin Version

v2.12.5

### Server Version

paper-1.20.6-138-master

### Describe the Bug

When player loads into server, SimpleScore spits out an error.

### Relevant Log Output

```shell
[22:14:48 ERROR]: Could not pass event PlayerJoinEvent to SimpleScore v3.12.5
java.lang.NullPointerException: Unable to create instance for class class net.minecraft.network.protocol.game.ClientboundSetObjectivePacket - true - com.comphenix.protocol.wrappers.WrappedStreamCodec[handle=net.minecraft.network.codec.StreamCodec$5@f6db284]
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.lambda$determineBestCreator$4(StructureCache.java:151) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newInstance(StructureCache.java:80) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:75) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:163) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:120) ~[ProtocolLib.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:30) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard$createScoreboard$1.invoke(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda$0(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:29) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore$default(ScoreboardManager.kt:86) ~[SimpleScore-3.12.5.jar:?]
        at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.listeners.PlayerListener.onPlayerJoin(PlayerListener.kt:18) ~[SimpleScore-3.12.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor345.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by RuiPereiraDev** [comment]
Hey! Sorry for the delayed response, but I've been away.

[SimpleScore v4](https://modrinth.com/plugin/simplescore/version/4.0.0) should resolve this issue as it no longer depends on ProtocolLib.
