### ISSUE TITLE
SimpleScore just stopped working randomly

### ISSUE THREAD

**Issue by imcoollol125** [r4g3baby/SimpleScore#86]
### Plugin Version

v3.12.5

### Server Version

Paper-1.20.4 (git-Paper-497)

### Describe the Bug

I just started my Minecraft Server and SimpleScore just stopped working out of nowhere.
![image](https://github.com/user-attachments/assets/6d86ff56-ae9d-4df8-8618-efa8b308ebf8)
As soon as a player joins the game SimpleScore instantly SPAMS the console with the error `[16:07:08 WARN]: [SimpleScore] Task #2793 for SimpleScore v3.12.5 generated an exception`
If the player leaves it stops.

### Relevant Log Output

```shell
[16:06:08] [Server thread/INFO]: iloveredston0[/127.0.0.1:57008] logged in with entity id 447 at ([loginworld]0.5603345687921385, 143.0, 11.5248209257172)
[16:06:08] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3449ms or 68 ticks behind
[16:06:09] [Server thread/WARN]: [SimpleScore] Task #1478 for SimpleScore v3.12.5 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib (1).jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib (1).jar:?]
	at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:154) ~[SimpleScore-3.12.5.jar:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.updateScoreboards(ScoreboardTask.kt:89) ~[SimpleScore-3.12.5.jar:?]
	at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda$7(ScoreboardTask.kt:72) ~[SimpleScore-3.12.5.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:06:09] [Server thread/WARN]: [SimpleScore] Task #1481 for SimpleScore v3.12.5 generated an exception
```

**Comment by imcoollol125** [comment]
It was a ProtocolLib bug.
